[DEFAULT]
enabled_backends=rbd-nvme,rbd-sata-ssd
default_volume_type=NVMe

[rbd-nvme]
volume_driver = cinder.volume.drivers.rbd.RBDDriver
volume_backend_name = rbd-nvme
rbd_pool = volumes
rbd_ceph_conf = /etc/ceph/ceph.conf
rados_connect_timeout = 5
rbd_user = {{ ceph_cinder_user }}
rbd_keyring_conf = ceph.client.cinder.keyring
rbd_secret_uuid = {{ cinder_rbd_secret_uuid }}
report_discard_supported = true

[rbd-sata-ssd]
volume_driver = cinder.volume.drivers.rbd.RBDDriver
volume_backend_name = rbd-sata-ssd
rbd_pool = volumes-sata-ssd
rbd_ceph_conf = /etc/ceph/ceph.conf
rados_connect_timeout = 5
rbd_user = {{ ceph_cinder_user }}
rbd_keyring_conf = ceph.client.cinder.keyring
rbd_secret_uuid = {{ cinder_rbd_secret_uuid }}
report_discard_supported = true
