[security_compliance]
change_password_upon_first_use = True
password_regex = ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{8,}$
password_regex_description = Passwords must contain at least 1 lowercase letter,
                             1 uppercase letter, 1 digit, and be a minimum
                             length of 8 characters.
lockout_failure_attempts = 5
lockout_duration = 1800
