[pci]
alias = { "vendor_id": "8086", "product_id": "e212", "device_type": "type-VF", "name": "Intel-Arc-Pro-B50-VF", "numa_policy": "preferred" }
alias = { "vendor_id": "10de", "product_id": "2231", "device_type": "type-PF", "name": "NVIDIA-A5000-24Q", "numa_policy": "preferred" }
alias = { "vendor_id": "10de", "product_id": "1e37", "device_type": "type-PF", "name": "TeslaT10", "numa_policy": "preferred" }
